### PR TITLE
feat(*): render list of AP templates

### PR DESCRIPTION
**Pull request by algomaster99**

### CODE REVIEW

**Comment by jolanglinais** [comment]
I think this looks good so far, are you ready for us to take a 👀 at it?

**Comment by algomaster99** [comment]
@irmerk yeah, sure. This only renders the list. The buttons in the templates don't work yet.

**Review by DianaLease — APPROVED** [review]
Nice! We'll want to iterate on the styling, add padding around the library component, etc, but this is a great start to get the component integrated with the Word add-in :)

**Comment by algomaster99** [comment]
@DianaLease thanks! I would focus more on styling once I am able to add text in the document. That is quite daunting task 😅

**Pull request merged**
