### PR TITLE
feat(src): retain listeners when document is reopened

### PR DESCRIPTION
**Pull request by algomaster99**
These changes will preserve the event listeners, which are added for detecting changes in values of the variable, on reopening the document. This will allow the user to share the document.

### CODE REVIEW

**Comment by jolanglinais** [comment]
How is this process going? Hesitant to look too much if it's a draft still.

**Comment by algomaster99** [comment]
@irmerk it's going great. I have to find a way to enumerate the variables so that I can attach the listeners accordingly. Yes, you don't need to review this now :sweat_smile:

**Review by jolanglinais — APPROVED** [review]
🧨

**Review by DianaLease — APPROVED** [review]
👏

**Pull request merged**
