### PR TITLE
feat(TemplateLibrary): add feature to upload template

### PR DESCRIPTION
**Pull request by algomaster99**
Signed-off-by: Aman Sharma <mannu.poski10@gmail.com>

These changes allow users to upload their own template **(must be compiled)**.

demo

We also need to show the error to user if the file uploaded is invalid. I can suggest two ways to do that:
1. Render the error in a dialog box something. https://docs.microsoft.com/en-us/office/dev/add-ins/develop/dialog-api-in-office-add-ins
2. Show the error inside the add-in.

### CODE REVIEW

**Comment by jolanglinais** [comment]
What is the current behavior if the uploaded file is invalid?

**Comment by algomaster99** [comment]
@irmerk nothing happens as of now. I was initially logging the error in the console but commented that too. 😅

**Comment by jolanglinais** [comment]
I would think that option 1 would be preferable, so as to not require further modification to the Library component from `web-components`

**Comment by jolanglinais** [comment]
@algomaster99 you can use this micropublish of the `Library`: `@accordproject/ui-components@0.93.2-20200730172709`

**Comment by algomaster99** [comment]
### Demo

bad-file

**Review by jolanglinais — APPROVED** [review]
I think this looks good! The `Office.context.ui.displayDialogAsync` is strange to me, but I suppose that's Word for ya. @DianaLease thoughts?

**Comment by algomaster99** [comment]
@irmerk 
@DianaLease suggested me to use `react-router` for creating other _route_ for displaying the error page. I did try it but it involved adding packages - `react-router` and `react-router-dom`. Although this is a better approach, I believe we should use this approach when we have a lot of error pages. Sounds overkill when we are doing only for one page. :sweat_smile: 
@DianaLease what do you think?

**Comment by DianaLease** [comment]
> @irmerk
> @DianaLease suggested me to use `react-router` for creating other _route_ for displaying the error page. I did try it but it involved adding packages - `react-router` and `react-router-dom`. Although this is a better approach, I believe we should use this approach when we have a lot of error pages. Sounds overkill when we are doing only for one page. 😅
> @DianaLease what do you think?

That sounds fine to me!

**Review by DianaLease — APPROVED** [review]

**Pull request merged**
